### ISSUE TITLE
add trailing slash option

### ISSUE THREAD

**Issue by pishgaman-org** [sullo/nikto#270] opened 2015-07-20 11:13 UTC
Hi

some websites rewrite their URIs to with or without trailing slash ones and nikto reports this redirections as found pages.
so it's needed an option to select nikto add trailing slash to URIs or not.

**Comment by sullo** [comment] 2015-08-09 17:27
I think we need some more information on this--some output from the scanner console and if possible a sample response with -D D option. Unless I'm missing something the tests in the DB shouldn't be matching 302 unless it's mis-determined that it's the "ok" response.

**Comment by pishgaman-org** [comment] 2015-08-09 19:24
For example if nikto checks blow url :
http://somesite.com/admin/
server remove trailing slash and next checks page exist or not. So page redirects to :
http://somesite.com/admin
And next shows 404 error.
But nikto thinks the page exists because 301 or 302 redirection occurred.

**Comment by tautology0** [comment] 2015-08-09 21:21
This is a duplicate of #8: https://github.com/sullo/nikto/issues/8

**Comment by pishgaman-org** [comment] 2015-08-10 06:15
no, they aren't same.
in my example nikto add admin/ to end of url and 302 occures. but if it was an option to remove trailing slash, nikto add admin to end of url and 404 occurs.

**Closed** 2021-07-13 03:06 UTC
