### ISSUE TITLE
False Positive/Negative: JAMon - Java Application Monitor Admin interface - 007303

### ISSUE THREAD

**Issue by digininja** [sullo/nikto#726] opened 2021-06-14 05:29 UTC
### Output of suspected false positive / negative

Post any useful information like the ID of the test causing the false positive.

### Debug output

Plugin ID 007303

The request to /JAMonAdmin.jsp gets a 302 response to same server /xssError.do.

This is from the save file:

```
HTTP/1.1 302 Found
date: Fri, 11 Jun 2021 13:58:27 GMT
server: Apache-Coyote/1.1
location: https://site.com/xssError.do
content-length: 0
set-cookie: SameSite=None; Expires=Fri, 11-Jun-2021 13:58:58 GMT; Path=/; Secure
set-cookie: JSESSIONID=1113B59xx73E2DA0; Path=/; Secure; HttpOnly
cache-control: max-age=0
expires: Fri, 11 Jun 2021 13:58:28 GMT
x-ua-compatible: IE=EmulateIE7
cache-tag: paw
p3p: policyref="http://www.site.com/w3c/p3p.xml", CP="NOI DSP COR NID PSAa OUR IND COM NAV STA" 
keep-alive: timeout=5, max=66
connection: Keep-Alive
```

But if I hit that URL with curl I get a 404.

The signature in the database looks like it is looking for a 200 and the page title, neither of which appear in either the 302 or 404.

**Comment by iasdeoupxe** [comment] 2021-06-16 19:30
Probably caused by the missing escaping of the pipe here:

```
"| JAMonAdmin |"
```

**Comment by digininja** [comment] 2021-06-16 19:33
I did wonder if they would be treated as OR but then figured they would
trigger on everything if it was an OR of an empty string.

**Comment by sullo** [comment] 2021-06-21 21:27
Indeed, likely because of the | as it should have been escaped. Resolved in both active branches.

**Closed by sullo** 2021-06-21 21:27 UTC
Labels: bug
