### ISSUE TITLE
Bug: Cannot scan from a file

### ISSUE THREAD

**Issue by dendrit3** [sullo/nikto#789] opened 2023-03-14 11:38 UTC
Good morning Nikto Team, I have encountered a bug this morning while working with the Nikto tool. The bug consists of not scanning servers from a file. I edited the file to include both https:// as well as the plain domain.

The Nikto Version is v2.1.6 which is what I am currently using, I haven't checked any other version to see if there are any bugs of this sort within any of them.

The steps to produce:
Create a TXT file listing all the servers that you wish to scan.
Start the Nikto tool via CLI
Add the the file to the host "-h" parameter.
Press Enter.

This should produce an error stating something along the lines of "IP  not found"

**Comment by sullo** [comment] 2023-03-14 11:53
Hello @dendrit3, I am unable to reproduce this with version 2.1.6:
![image](https://user-images.githubusercontent.com/1474884/224992916-ecd48f1c-daa0-46be-9ea1-1ceab0f38c28.png)

Please validate that the file is readable by your user, and that the name actually resolves.

**Comment by dendrit3** [comment] 2023-03-14 11:56
I will look at here at some point, maybe I configured something wrong. If anything, else pops up I will let Nikto team know.

**Comment by sullo** [comment] 2023-03-14 11:57
I'll close this for now, but please reopen if you still have a problem.

**Closed by sullo** 2023-03-14 11:57 UTC
Labels: bug
