### ISSUE TITLE
Update ETag parser for Apache > 2.3.14

### ISSUE THREAD

**Issue by wireghoul** [sullo/nikto#477] opened 2017-05-17 08:21 UTC
After Apache version 2.3.14 the default value of the ETag header has excluded the inode value.

See https://httpd.apache.org/docs/2.4/mod/core.html#fileetag for details. It shouldn't take much to add another if statement and run some tests. I'll try to get to it unless someone beats me to it.

**Comment by sullo** [comment] 2017-05-20 03:42
Duplicate of #469

**Closed by sullo** 2017-05-20 03:42 UTC
