### ISSUE TITLE
Scanning an HTTPS target doesn't work when using a HTTP proxy

### ISSUE THREAD

**Issue by Sjord** [sullo/nikto#501] opened 2017-10-16 11:32 UTC
Scanning an HTTPS target with a HTTP proxy fails:

```
./nikto.pl -useproxy=http://127.0.0.1:8080/ -host=https://www.example.com/ 
- Nikto v2.1.6
---------------------------------------------------------------------------
+ ERROR: Proxy error: opening stream: can't connect: proxy connect failed: proxy connect to 127.0.0.1:8080 failed: Invalid argument at /var/lib/nikto/plugins/LW2.pm line 5157.
; Invalid argument at /var/lib/nikto/plugins/LW2.pm line 5157.
: Invalid argument
```

Scanning a HTTP target with a HTTP proxy works correctly.

**Comment by kkirsche** [comment] 2017-11-09 22:56
Same issue here

**Comment by Sjord** [comment] 2017-11-22 14:45
This issue only appears with the Net::SSL engine. A workaround is to use the SSLeay engine. Put the following in nikto.conf:

    LW_SSL_ENGINE=SSLeay

**Comment by Sjord** [comment] 2017-11-22 20:35
It seems that this is a bug or limitation of Net::SSL, or in the way nikto uses it:

```
$ HTTPS_PROXY=http://localhost:8080 perl -e "use Net::SSL; print(Net::SSL->new(PeerAddr => "badssl.com", PeerPort => 443));"
proxy connect failed: proxy connect to localhost:8080 failed: Address family not supported by protocol at -e line 1.
; Address family not supported by protocol at -e line 1.
```

@nanis, can you say something about this?

**Comment by Sjord** [comment] 2017-11-22 20:57
It seems Net::SSL calls `IO::Socket::IP->connect` [here](https://github.com/nanis/Crypt-SSLeay/blob/0.73_04/lib/Net/SSL.pm#L306), passing the port and address:

    $self->SUPER::connect($proxy_port, $proxy_addr)

However, [`connect`](https://github.com/Perl/perl5/blob/blead/cpan/IO-Socket-IP/lib/IO/Socket/IP.pm#L703) expects one parameter and passes that to perl's [connect](http://perldoc.perl.org/functions/connect.html):

    my ( $addr ) = @_;
    return connect( $self, $addr ) unless defined $timeout;

Note that the second parameter, `$proxy_addr`, is gone and only the port number is passed to connect.

**Comment by Sjord** [comment] 2017-11-23 09:44
Stack trace:

```
Trace begun at /usr/share/perl/5.24/IO/Socket/IP.pm line 439
IO::Socket::IP::connect('Net::SSL=GLOB(0x559d587b2868)', 8080, '^?^@^@^A') called at /usr/lib/x86_64-linux-gnu/perl5/5.24/Net/SSL.pm line 306
Net::SSL::proxy_connect_helper('Net::SSL=GLOB(0x559d587b2868)', '^J^@^_M-^P^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@') called at /usr/lib/x86_64-linux-gnu/perl5/5.24/Net/SSL.pm line 95
eval {...} at /usr/lib/x86_64-linux-gnu/perl5/5.24/Net/SSL.pm line 95
Net::SSL::connect('Net::SSL=GLOB(0x559d587b2868)', '^J^@^_M-^P^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@') called at /usr/share/perl/5.24/IO/Socket/IP.pm line 385
IO::Socket::IP::setup('Net::SSL=GLOB(0x559d587b2868)') called at /usr/share/perl/5.24/IO/Socket/IP.pm line 346
IO::Socket::IP::_io_socket_ip__configure('Net::SSL=GLOB(0x559d587b2868)', 'HASH(0x559d572f2938)') called at /usr/share/perl/5.24/IO/Socket/IP.pm line 143
IO::Socket::IP::configure('Net::SSL=GLOB(0x559d587b2868)', 'HASH(0x559d572f2938)') called at /usr/lib/x86_64-linux-gnu/perl5/5.24/Net/SSL.pm line 70
Net::SSL::configure('Net::SSL=GLOB(0x559d587b2868)', 'HASH(0x559d572f2938)') called at /usr/lib/x86_64-linux-gnu/perl/5.24/IO/Socket.pm line 48
IO::Socket::new('Net::SSL', 'Timeout', 10, 'PeerAddr', 'localhost', 'PeerPort', 8123) called at /usr/share/perl/5.24/IO/Socket/IP.pm line 110
IO::Socket::IP::new('Net::SSL', 'PeerAddr', 'localhost', 'PeerPort', 8123, 'Timeout', 10) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/Net/SSL.pm line 38
Net::SSL::new('Net::SSL', 'PeerAddr', 'localhost', 'PeerPort', 8123, 'Timeout', 10) called at /var/lib/nikto/plugins/LW2.pm line 5157
eval {...} at /var/lib/nikto/plugins/LW2.pm line 5152
LW2::_stream_ssl_open('LW2::stream=HASH(0x559d57b75df8)', 'HASH(0x559d5754f7e8)') called at (eval 31) line 1
LW2::__ANON__('HASH(0x559d5754f7e8)') called at /var/lib/nikto/plugins/LW2.pm line 2496
LW2::http_do_request('HASH(0x559d5754f7e8)', 'HASH(0x559d57621330)') called at /var/lib/nikto/plugins/LW2.pm line 3374
eval {...} at /var/lib/nikto/plugins/LW2.pm line 3371
LW2::http_do_request_timeout('HASH(0x559d5754f7e8)', 'HASH(0x559d57621330)') called at /var/lib/nikto/plugins/nikto_core.plugin line 2096
main::proxy_check('HASH(0x559d57cc1980)') called at /var/lib/nikto/plugins/nikto_core.plugin line 1544
main::port_check(1511430224, 'localhost', 'localhost', 8123, undef, undef) called at /usr/bin/nikto line 107
```

**Comment by wireghoul** [comment] 2018-01-22 20:20
I think we may have finally found the root cause of epoch time as hostname @sullo, see the last line of the stack trace

**Comment by sullo** [comment] 2018-02-07 03:17
Ok there are 2 failures here. One is that resolve() returns the name as the ip if -useproxy is set, which was a pretty hackish way to proceed on a scan letting the proxy resolve it (which is the right way). Failure 2 is port_check() tries to connect to it even if -useproxy is set.  And I guess failure 3 was letting this sit here for a few months. 

Committing a change which fixes both of those first two situations (resolve() now returns no IP if using a proxy, and port_check() doesn't happen if using a proxy). Initial testing seems to be ok having $mark-{'ip'} be undefined if we're using a proxy. This may make for some odd reports (where IP is blank) but I don't see any other problems. 

There is potential downstream breakage with anything parsing the XML or consuming SQL which expects the IP to be 'not null' but setting to any value (such as 127.0.0.1) would be a lie.

**Comment by sullo** [comment] 2018-02-07 03:18
Oh yeah here's a test of google.com with https & proxy:
`$ ./nikto.pl -h http://www.google.com/ -useproxy http://localhost:8080/
- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          
+ Target Hostname:    www.google.com
+ Target Port:        80
+ Start Time:         2018-02-06 22:17:44 (GMT-5)
---------------------------------------------------------------------------
+ Server: gws
...`

**Comment by sullo** [comment] 2018-02-07 03:50
So my fixes weren't quite what was needed. Something else is still going, so reverting for now as I think that did break other things.

**Comment by rajiv2790** [comment] 2018-03-20 23:47
FWIW, I am getting this error while scanning HTTP via HTTP proxy too

**Comment by saatomic** [comment] 2018-04-20 07:53
still having this issue.

**Comment by digininja** [comment] 2018-08-10 08:57
Nudge, I just hit this as well.

**Comment by h4knet** [comment] 2019-11-14 13:50
Hello, I can sadly confirm the problem is still present as of november 2019 with nikto v2.1.6.

**Comment by MMquant** [comment] 2021-03-12 10:57
Problem still present with nikto v2.1.6 and v2.0.0

**Comment by nu11secur1ty** [comment] 2021-03-12 12:34
> Ok there are 2 failures here. One is that resolve() returns the name as the ip if -useproxy is set, which was a pretty hackish way to proceed on a scan letting the proxy resolve it (which is the right way). Failure 2 is port_check() tries to connect to it even if -useproxy is set. And I guess failure 3 was letting this sit here for a few months.
> 
> Committing a change which fixes both of those first two situations (resolve() now returns no IP if using a proxy, and port_check() doesn't happen if using a proxy). Initial testing seems to be ok having $mark-{'ip'} be undefined if we're using a proxy. This may make for some odd reports (where IP is blank) but I don't see any other problems.
> 
> There is potential downstream breakage with anything parsing the XML or consuming SQL which expects the IP to be 'not null' but setting to any value (such as 127.0.0.1) would be a lie.

:)

**Comment by tautology0** [comment] 2021-07-22 08:50
I've tried to reproduce this situation since the latest fixes in both 2.1.6 and 2.5.0 and it currently works for me - things are going through an off server burp to the correct destination.

Could somebody else try for me so I can either try and fix or close?

**Comment by digininja** [comment] 2021-07-22 09:10
Completely broken for me, what am I doing wrong?

```
robin@flint program $ ./nikto.pl -host http://digi.ninja -useproxy http://localhost:8080
- Nikto v2.5.0
---------------------------------------------------------------------------
+ ERROR: Proxy error: opening stream: can't connect: proxy connect failed: proxy connect to localhost:8080 failed: Invalid argument at /home/robin/tools/web/nikto/program/plugins/LW2.pm line 5254.
; Invalid argument at /home/robin/tools/web/nikto/program/plugins/LW2.pm line 5254.
: Invalid argument
```

Burp is up:

```
robin@flint program $ curl localhost:8080
<html><head><title>Burp Suite Professional</title>
<style type="text/css">
body { background: #dedede; font-family: Arial, sans-serif; color: #404042; -webkit-font-smoothing: antialiased; }
#container { padding: 0 15px; margin: 10px auto; background-color: #ffffff; }
a { word-wrap: break-word; }
```

When I was originally having this problem, I think Burp worked OK, it was HTTPS over Squid that failed for me. The details are in a ticket somewhere, but it was to do with sending a CONNECT when it shouldn't I think.

**Comment by tautology0** [comment] 2021-07-22 11:05
That line 5254 is part of the Net::SSL->new() call which makes me suspect it's not using Net::SSLeay for you. Could you try:

`perl -e 'use Net::SSLeay';`

And see whether you get an error?

**Comment by digininja** [comment] 2021-07-22 11:28
No error

![image](https://user-images.githubusercontent.com/117081/126632309-7e9e0eb7-3ca8-4671-a304-db442b01305c.png)

**Comment by tautology0** [comment] 2021-07-22 13:52
So you have Net::SSLeay installed - what about if you change nikto.conf to explicitly use Net::SSLeay?

**Comment by digininja** [comment] 2021-07-22 13:55
That works through both Burp and Squid.

HTTPS through Squid has never worked before so something has definitely
been fixed.

**Comment by sullo** [comment] 2021-07-22 18:16
Can confirm working on 2.5.0 branch with both Burp and another proxy.

**Comment by tautology0** [comment] 2021-07-22 21:17
Cool; so for some reason digininja's version of Nikto selected Net::SSL instead of Net:SSLeay. This could be a pig to debug, I'm tempted to close this with the work around being "set nikto.conf to use Net::SSLeay" if others have the same problem.

**Closed by tautology0** 2021-07-22 21:17 UTC
Labels: bug
