### ISSUE TITLE
consider tagging a new git release

### ISSUE THREAD

**Issue by anthraxx** [sullo/nikto#655] opened 2020-02-11 15:03 UTC
Hi,
Right now it looks like the last release is from Jul 9, 2015. However since than a lot of work has been made, it would be nice to reflect the changes in a new release via a git tag. This way the new commits would be picket up by distributions and i could ship a new version for our users as well.
thx for all the work.

**Comment by NicolasCARPi** [comment] 2020-09-21 01:38
Dear maintainers, is there a blocking issue for releasing a new tag/version? Feels a bit weird to have only one tag in 2015 for an active project.

Cheers :)

**Comment by NicolasCARPi** [comment] 2020-09-21 01:45
This can be closed as duplicate of #590.

**Closed** 2020-09-21 07:45 UTC
