### ISSUE TITLE
404 When using -update option

### ISSUE THREAD

**Issue by cgtopher** [sullo/nikto#375] opened 2016-05-11 14:26 UTC
I get the following when using the update option: 

```
~/nikto/program$ ./nikto.pl -update
+ ERROR (404): Unable to get cirt.net/nikto/UPDATES/2.1.6/versions.txt
```

Confirmed that I'm also not able to reach that URL in a browser.

**Comment by sullo** [comment] 2016-05-11 15:42
use 'git pull' instead since you're running the git version (which his most
current).

On Wed, May 11, 2016 at 10:26 AM, Chris Gaunt <notifications@github.com>
wrote:

> I get the following when using the update option:
>
> `~/nikto/program$ ./nikto.pl -update
>
>    - ERROR (404): Unable to get cirt.net/nikto/UPDATES/2.1.6/versions.txt`
>    <http://cirt.net/nikto/UPDATES/2.1.6/versions.txt>
>
> Confirmed that I'm also not able to reach that URL in a browser.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sullo/nikto/issues/375>
>



-- 

http://cirt.net     |      http://richsec.com/

**Comment by cgtopher** [comment] 2016-05-11 17:54
Ah yes, that makes sense. I may write a patch that detects if user is running git version, and have it use git pull, if that's agreeable. Thanks!

**Comment by sullo** [comment] 2016-05-12 03:03
not a bad idea--just ask them first. and we'll back that out when (if?)
2.2.0 comes out with a better update option. thanks!

On Wed, May 11, 2016 at 1:54 PM, Chris Gaunt <notifications@github.com>
wrote:

> Ah yes, that makes sense. I may write a patch that detects if user is
> running git version, and have it use git pull, if that's agreeable. Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sullo/nikto/issues/375#issuecomment-218538187>
>



-- 

http://cirt.net     |      http://richsec.com/

**Comment by j0sh3rs** [comment] 2018-02-05 02:20
This issue exists regardless of whether someone is running the git version.  Pulling the release 2.1.6 continues to have this error.  The problem is that the `program/nikto.pl` specifically references version 2.1.6, but the webserver hosting the updates (https://cirt.net/nikto/UPDATES/) does not have a 2.1.6 directory.

For anyone else running into this problem (until it gets fixed by a new directory on the hosting server), you can manually edit `program/nikto.pl` and adjust the `$VARIABLES{'version'}` variable to `2.1.5` to get updates to succeed.

**Comment by sullo** [comment] 2018-02-05 03:32
created 2.1.6/versions.txt to tell people to update via git

**Closed** 2019-03-09 03:54 UTC
